# Generated by Django 2.2.3 on 2019-07-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190712_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='idade',
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pet_lost',
        ),
    ]
