# Generated by Django 2.2.3 on 2019-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
