# Generated by Django 2.2.3 on 2019-07-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190712_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
    ]
