# Generated by Django 2.2.3 on 2019-07-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
